# Generated by Django 3.0.7 on 2020-06-08 00:36

import authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_names', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dod', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('photo', models.ImageField(blank=True, upload_to=authors.models.upload_location)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
