# Generated by Django 3.0.7 on 2020-09-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20200912_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_featured',
        ),
    ]
