# Generated by Django 5.2.11 on 2026-02-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_remove_author_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
