# Generated by Django 3.0.7 on 2020-06-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='other_authors',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
