# Generated by Django 3.0.7 on 2020-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200608_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
