# Generated by Django 3.0.7 on 2020-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200925_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='ABC', max_length=3),
            preserve_default=False,
        ),
    ]
