# Generated by Django 3.0.7 on 2020-09-25 19:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('books', '0006_auto_20200925_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='secondary_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='secondary_tags', through='books.TaggedSecondaryBook', to='taggit.Tag', verbose_name='secondary tags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='user_tags', through='books.UserTaggedBook', to='taggit.Tag', verbose_name='user tags'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
