# Generated by Django 3.0.7 on 2020-06-08 21:36

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='photo',
            field=models.ImageField(blank=True, upload_to=books.models.upload_genre_location),
        ),
    ]
