# Generated by Django 3.0.7 on 2020-06-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200608_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
