# Generated by Django 3.0.7 on 2020-06-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_genre_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='primary_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Genre'),
        ),
    ]
