# Generated by Django 3.0.7 on 2020-06-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_primary_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='primary_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Genre'),
        ),
    ]
