# Generated by Django 3.0.7 on 2020-06-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200610_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='primary_genre',
        ),
    ]
