# Generated by Django 3.0.7 on 2020-09-28 11:43

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20200928_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='secondary_tags',
        ),
        migrations.AlterField(
            model_name='book',
            name='primary_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='books.BookPrimaryTag', to='books.PrimaryTags', verbose_name='primary tags'),
        ),
        migrations.DeleteModel(
            name='TaggedSecondaryBook',
        ),
    ]
