# Generated by Django 3.0.7 on 2020-06-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_book_primary_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('bk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('gnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(through='books.Order', to='books.Genre'),
        ),
    ]
