# Generated by Django 3.0.7 on 2020-06-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200610_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
