# Generated by Django 3.0.7 on 2020-09-28 11:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200928_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Secondary Tag',
                'verbose_name_plural': 'Secondary Tags',
            },
        ),
        migrations.CreateModel(
            name='BookSecondaryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_secondary_tags', to='books.SecondaryTags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='secondary_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='books.BookSecondaryTag', to='books.SecondaryTags', verbose_name='secondary tags'),
        ),
    ]
