# Generated by Django 3.0.7 on 2020-09-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200928_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_tags',
        ),
        migrations.RemoveField(
            model_name='primarytags',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='secondarytags',
            name='categories',
        ),
        migrations.DeleteModel(
            name='UserTaggedBook',
        ),
    ]
