# Generated by Django 3.0.7 on 2020-06-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200610_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
