# Generated by Django 3.0.7 on 2020-09-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200929_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksecondarytag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='booksecondarytag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='book',
            name='primary_tags',
        ),
        migrations.RemoveField(
            model_name='book',
            name='secondary_tags',
        ),
        migrations.DeleteModel(
            name='BookPrimaryTag',
        ),
        migrations.DeleteModel(
            name='BookSecondaryTag',
        ),
        migrations.DeleteModel(
            name='PrimaryTags',
        ),
        migrations.DeleteModel(
            name='SecondaryTags',
        ),
    ]
