# Generated by Django 3.0.7 on 2020-06-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20200610_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='primary_genre',
            new_name='genre',
        ),
    ]
