# Generated by Django 3.0.7 on 2020-06-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200610_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre_featured',
            field=models.BooleanField(default=False),
        ),
    ]
