# Generated by Django 3.0.7 on 2020-09-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20200929_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktags',
            name='category2',
        ),
        migrations.AddField(
            model_name='booktags',
            name='band',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'General fiction main'), (2, 'General fiction secondary'), (3, 'Non-fiction'), (4, 'Sci-fi and Fantasy'), (5, 'Children and Middle Grade'), (6, 'Teen and Young adult')], default=99, help_text='Tag Band'),
        ),
    ]
