# Generated by Django 3.0.7 on 2020-09-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_remove_booktags_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktags',
            options={'ordering': ('band', 'name'), 'verbose_name': 'book tag', 'verbose_name_plural': 'book tags'},
        ),
    ]
