# Generated by Django 3.0.7 on 2020-06-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_bookinstance2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance2',
            options={'ordering': ['due_back'], 'verbose_name': 'Book Instance'},
        ),
    ]
