# Generated by Django 3.0.7 on 2020-06-18 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20200616_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 18, 17, 42, 19, 184301, tzinfo=utc), null=True),
        ),
    ]
