# Generated by Django 3.0.7 on 2020-09-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20200930_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_tags',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.DeleteModel(
            name='BookTag',
        ),
        migrations.DeleteModel(
            name='BookTags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
