# Generated by Django 3.0.7 on 2020-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20200618_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
