# Generated by Django 3.0.7 on 2020-09-30 17:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20200930_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('band', models.PositiveIntegerField(blank=True, choices=[(1, 'General fiction main'), (2, 'General fiction secondary'), (3, 'Non-fiction'), (4, 'Sci-fi and Fantasy'), (5, 'Children and Middle Grade'), (6, 'Teen and Young adult')], default=99, help_text='Tag Band')),
            ],
            options={
                'verbose_name': 'book tag',
                'verbose_name_plural': 'book tags',
                'ordering': ('band', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('tags_included', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tags', to='books.BookTags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='books.BookTag', to='books.BookTags', verbose_name='book tags'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.Category'),
        ),
    ]
