# Generated by Django 3.0.7 on 2020-10-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20200930_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance2',
            options={'ordering': ['book__title'], 'verbose_name': 'Book Instance'},
        ),
        migrations.AlterField(
            model_name='bookinstance2',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], db_index=True, default='a', max_length=1),
        ),
    ]
