# Generated by Django 3.0.7 on 2020-06-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20200618_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance2',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
