# Generated by Django 3.0.7 on 2020-10-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_auto_20201008_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance2',
            options={'ordering': ['status', 'book__title'], 'verbose_name': 'Book Instance'},
        ),
    ]
