# Generated by Django 3.0.7 on 2020-06-23 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20200623_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 23, 13, 43, 8, 735931, tzinfo=utc), null=True),
        ),
    ]
