# Generated by Django 3.0.7 on 2020-06-23 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_bookinstance_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='time_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
