# Generated by Django 3.0.7 on 2024-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20241003_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
