# Generated by Django 3.0.7 on 2024-10-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_subcategory_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'subcategories'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_for_sale',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='book',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.SubCategory'),
        ),
    ]
