# Generated by Django 3.0.7 on 2024-10-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_auto_20241003_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
