# Generated by Django 3.0.7 on 2024-10-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_bookforsale_salecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookforsale',
            options={'ordering': ('title',), 'verbose_name_plural': 'books for sale'},
        ),
    ]
