# Generated by Django 3.0.7 on 2024-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_auto_20241004_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookforsale',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
    ]
