# Generated by Django 3.0.7 on 2020-07-17 12:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('books', '0035_auto_20200717_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='books.TaggedBook', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
