# Generated by Django 3.0.7 on 2024-10-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_auto_20241004_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookforsale',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
