# Generated by Django 3.0.7 on 2020-07-17 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_auto_20200717_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='time_created',
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
