# Generated by Django 3.0.7 on 2024-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_auto_20241004_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookforsale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
