# Generated by Django 3.0.7 on 2024-10-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_auto_20241004_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsale',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
