# Generated by Django 3.0.7 on 2024-10-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_bookforsale_isbn13'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookforsale',
            old_name='isbn13',
            new_name='isbn',
        ),
    ]
