# Generated by Django 3.0.7 on 2020-07-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_auto_20200717_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance2',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
