# Generated by Django 3.0.7 on 2024-11-18 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_auto_20241004_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tags_included',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
    ]
