# Generated by Django 3.0.7 on 2024-11-20 16:31

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_auto_20241118_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookforsale',
            name='photo',
            field=models.ImageField(blank=True, upload_to=books.models.upload_book_for_sale_image_location),
        ),
    ]
