# Generated by Django 3.0.7 on 2020-07-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_auto_20200717_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance2',
            name='book_type',
            field=models.CharField(blank=True, choices=[('p', 'Paperback'), ('h', 'Hardcover'), ('o', 'Oversized')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='bookinstance2',
            name='isbn10',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookinstance2',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance2',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='books.Book'),
        ),
    ]
