# Generated by Django 3.0.7 on 2020-07-21 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0044_auto_20200721_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='other_authors',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='usertaggedbook',
            name='tagger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
