# Generated by Django 5.2.11 on 2026-02-17 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_remove_author_is_featured'),
        ('books', '0044_alter_taggedbook_tag'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created'], name='book_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', 'created'], name='book_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='booktag',
            index=models.Index(fields=['tag', 'content_object'], name='booktag_tag_book_idx'),
        ),
        migrations.AddIndex(
            model_name='booktag',
            index=models.Index(fields=['content_object', 'tag'], name='booktag_book_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='booktag',
            constraint=models.UniqueConstraint(fields=('content_object', 'tag'), name='uniq_booktag'),
        ),
    ]
