# Generated by Django 5.2.11 on 2026-06-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0045_book_book_created_desc_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance2',
            options={'ordering': ['book__title'], 'verbose_name': 'Book Instance'},
        ),
        migrations.RemoveField(
            model_name='bookinstance2',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='bookinstance2',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='bookinstance2',
            name='status',
        ),
    ]
