# Generated by Django 3.0.7 on 2020-07-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0045_auto_20200721_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='isbn_latest',
        ),
    ]
