# Generated by Django 5.2.11 on 2026-06-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0046_alter_bookinstance2_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='bookinstance2',
            options={'ordering': ['book__title'], 'verbose_name': 'book copy', 'verbose_name_plural': 'book copies'},
        ),
        migrations.DeleteModel(
            name='TaggedBook',
        ),
    ]
