# Generated by Django 5.2.11 on 2026-06-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0047_remove_book_tags_alter_bookinstance2_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags_included',
        ),
    ]
