# Generated by Django 5.2.11 on 2026-07-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0049_redesign_book_tag_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktags',
            name='band',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Audience / age'), (20, 'Broad genres'), (30, 'Subgenres & genre flavours'), (40, 'Themes & relationships'), (50, 'Setting, place & history'), (60, 'Form, style & format'), (70, 'SFF / supernatural elements'), (80, 'Subjects & interests'), (99, 'Unassigned / needs review')], db_index=True, default=99, help_text='Tag band'),
        ),
    ]
