# Generated by Django 5.2.11 on 2026-07-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueDataDownloadStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='catalogue_csv', max_length=50, unique=True)),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'catalogue data download stat',
                'verbose_name_plural': 'catalogue data download stats',
            },
        ),
    ]
