# Generated by Django 3.0.7 on 2020-09-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200912_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-reservation_date',)},
        ),
    ]
