# Generated by Django 5.2.11 on 2026-06-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200913_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
