# Generated by Django 3.0.7 on 2020-06-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200615_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='can_collect',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
