# Generated by Django 3.0.7 on 2020-06-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20200621_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
