# Generated by Django 3.0.7 on 2020-06-11 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=200)),
                ('date_taken_out', models.DateField(default=datetime.datetime.now)),
                ('date_returned', models.DateField(blank=True)),
            ],
        ),
    ]
