# Generated by Django 3.0.7 on 2020-06-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
