# Generated by Django 3.0.7 on 2020-10-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='memb_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
