# Generated by Django 3.0.7 on 2020-10-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201014_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='memb_num',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
