# Generated by Django 3.0.7 on 2020-10-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201014_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='memb_num',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='membership number'),
        ),
    ]
