# Generated by Django 3.0.7 on 2020-10-14 14:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201014_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_location, verbose_name='profile photo'),
        ),
    ]
