# Generated by Django 3.2 on 2026-01-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201014_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
