# Generated by Django 3.0.7 on 2020-06-15 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_instance_id', models.IntegerField()),
                ('date_taken_out', models.DateField(default=django.utils.timezone.now)),
                ('date_returned', models.DateField(blank=True)),
            ],
        ),
    ]
