# Generated by Django 3.0.7 on 2020-06-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records2', '0002_record_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='book_title',
            field=models.CharField(blank=True, default='title', max_length=200),
        ),
    ]
