# Generated by Django 3.0.7 on 2020-06-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records2', '0003_auto_20200615_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
