# Generated by Django 3.0.7 on 2020-06-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records2', '0004_auto_20200616_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('-date_returned',)},
        ),
    ]
