# Generated by Django 3.0.7 on 2020-09-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records2', '0005_auto_20200628_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
