# Generated by Django 3.0.7 on 2020-10-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records2', '0006_auto_20200912_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='extended',
            field=models.BooleanField(default=False),
        ),
    ]
