# Generated by Django 5.2.11 on 2026-06-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records2', '0007_record_extended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
